feat: create setup lint and prettier
podcodar/todo-list pull request #1
Opened 2022-03-25 15:51 UTC by Filipe-barbosa

Cria setup de lint para o projeto

2022-03-25 16:46 UTC, marco-souza requested changes
Alem de configurar linter, recomendo das duas uma:
- adicionar Husky e definir os comandos de lint pra rodarem pre-commit, pra evitar commit feio
- adicionar um CI para barrar coisas fora do lint.

Eu vejo a primeira como mais negocio, pois evita ate mesmo do commit acontecer se tiver errado

Alem disso, não vi nenhum pacote ser adicionado (eslint, prettier, plugins, etc). Chegou a testar e ver se ta funcionando?

Recomendo tambem criar um script `lint` ou `fmt` no `package.json`.

2022-03-25 16:46 UTC, marco-souza commented on todo-list/.eslintrc.yml
> +  react-hooks/rules-of-hooks: error
Tpdps esses packages foram instalados? não tem alteração no package json

2022-03-25 16:46 UTC, marco-souza commented on todo-list/.prettierignore
> +.pnp.js
tem muita coisa aqui que não usamos. Eu gosto de geralmente manter a configuração ao mínimo, mas como é um projeto rapido, não faz tanta diferença.

2022-03-25 17:11 UTC, marco-souza commented
Outra coisa, pq as configs estao dentro de uma pasta e não na raiz do projeto?

2022-03-28 12:46 UTC, frattezi reviewed
I think you fixed most of marco's assertions.

One thing I don't understand is why the project is inside a `todo-list` folder. This makes the structure to be:
```bash
todo-list/
| -> todo-list/
| - - > src
| - - > ...
```
which makes no sense to be, you could spread the files directly in the repository source, like 
```bash
todo-list/
| - > src
| - > ...
```

2022-03-28 12:48 UTC, frattezi commented
> I think you fixed most of marco's assertions.
> 
> One thing I don't understand is why the project is inside a `todo-list` folder. This makes the structure to be:
> 
> ```shell
> todo-list/
> | -> todo-list/
> | - - > src
> | - - > ...
> ```
> 
> which makes no sense to be, you could spread the files directly in the repository source, like
> 
> ```shell
> todo-list/
> | - > src
> | - > ...
> ```

Lol, looks like the viewer missleaded me, you already moved the files, tyty

2022-03-28 12:59 UTC, frattezi reviewed
By loading the project locally in my system:
- Freshly installed repository after download.
- Prettier, Eslint and Typescript extensions installed in vscode

I'm having this errors for every `jsx` file:

![Screenshot from 2022-03-28 09-54-46](https://user-images.githubusercontent.com/14007745/160402586-9782875b-66b8-40d1-b806-09f50f8d4505.png)
![Screenshot from 2022-03-28 09-53-54](https://user-images.githubusercontent.com/14007745/160402596-9f712d91-114c-4ab1-8f6b-fd7d14bdf06b.png)

**Error messages:**
- "JSX not allowed in files with extension '.tsx'"
- "Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`"

Am I missing something?

2022-03-28 12:59 UTC, frattezi commented on package.json
> +    "eject": "react-scripts eject",
Ia ser massa ter um script para o linter aqui, não? o/

2022-03-28 14:10 UTC, marco-souza approved these changes

2022-03-28 14:10 UTC, merged